[global]
address = "127.0.0.1"
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "normal"
secret_key = "secret"

[global.github]
events = ["issues", "pull_request"]
repos = ["mine/a-project"]